/* -------------------------------------------------------------------------- */
/* License                                                                     */
/* -------------------------------------------------------------------------- */

export type LicenseType = "trial" | "monthly" | "yearly" | "lifetime";

export type LicenseStatus =
  | "pending"
  | "active"
  | "expired"
  | "suspended"
  | "revoked";

export type ActivationStatus = "active" | "deactivated" | "blocked";

export type License = {
  id: string;

  /**
   * Human-readable license key.
   * Example: IVAC-XXXX-XXXX-XXXX
   */
  licenseKey: string;

  type: LicenseType;
  status: LicenseStatus;

  /**
   * Customer/account that owns the license.
   */
  userId?: string;

  /**
   * Maximum number of devices that can be activated.
   */
  maxActivations: number;

  /**
   * Current number of active devices.
   */
  activeActivations: number;

  startsAt?: string;
  expiresAt?: string;

  /**
   * Lifetime licenses may have no expiration date.
   */
  isLifetime: boolean;

  createdAt: string;
  updatedAt: string;
};

/* -------------------------------------------------------------------------- */
/* License Activation                                                         */
/* -------------------------------------------------------------------------- */

export type LicenseActivation = {
  id: string;
  licenseId: string;

  /**
   * User/account associated with this activation.
   */
  userId?: string;

  /**
   * Unique identifier generated by the extension installation.
   */
  deviceId: string;

  /**
   * Optional device information for administration.
   */
  deviceName?: string;
  platform?: string;
  browser?: string;
  extensionVersion?: string;

  status: ActivationStatus;

  activatedAt: string;
  lastSeenAt?: string;
  deactivatedAt?: string;

  /**
   * Server-generated token used by the extension
   * to authenticate an activated installation.
   */
  activationToken?: string;
};

/* -------------------------------------------------------------------------- */
/* License Validation                                                         */
/* -------------------------------------------------------------------------- */

export type LicenseValidation = {
  id: string;
  licenseId: string;
  activationId?: string;

  valid: boolean;

  /**
   * Why validation succeeded/failed.
   */
  reason?:
    | "valid"
    | "invalid_key"
    | "expired"
    | "suspended"
    | "revoked"
    | "activation_limit"
    | "device_blocked";

  deviceId?: string;
  ipAddress?: string;

  createdAt: string;
};

/* -------------------------------------------------------------------------- */
/* License Event / Audit Log                                                  */
/* -------------------------------------------------------------------------- */

export type LicenseEventType =
  | "created"
  | "activated"
  | "validated"
  | "deactivated"
  | "expired"
  | "suspended"
  | "revoked"
  | "renewed"
  | "activation_blocked";

export type LicenseEvent = {
  id: string;
  licenseId: string;
  activationId?: string;

  type: LicenseEventType;

  message?: string;
  metadata?: string;

  createdAt: string;
};

/* -------------------------------------------------------------------------- */
/* License Settings                                                           */
/* -------------------------------------------------------------------------- */

export type LicenseSettings = {
  id: string;

  /**
   * Default trial period in days.
   */
  trialDays: number;

  /**
   * How often the extension should validate its license.
   */
  validationIntervalHours: number;

  /**
   * Whether the extension can continue working temporarily
   * when the license server is unavailable.
   */
  offlineGracePeriodHours: number;

  updatedAt: string;
};
