import { Copy, KeyRound, Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import type { License, LicenseType } from "../types/license";
import { createLicense, deleteLicense, renewLicense, updateLicenseStatus } from "../services/license.service";
import StatusBadge from "../components/StatusBadge";
import Modal from "../components/Modal";
import { formatDate } from "../utils/format";

export default function Licenses({licenses,onRefresh}:{licenses:License[];onRefresh:()=>Promise<void>}) {
  const [search,setSearch]=useState(""); const [open,setOpen]=useState(false); const [created,setCreated]=useState(""); const [type,setType]=useState<LicenseType>("monthly"); const [max,setMax]=useState(1); const [name,setName]=useState(""); const [email,setEmail]=useState("");
  const filtered=useMemo(()=>{const q=search.toLowerCase();return licenses.filter(x=>[x.licenseKey,x.customerName,x.customerEmail,x.type,x.status].filter(Boolean).join(" ").toLowerCase().includes(q))},[licenses,search]);
  async function submit(e:React.FormEvent){e.preventDefault();const l=await createLicense({type,maxActivations:max,customerName:name,customerEmail:email});setOpen(false);setCreated(l.licenseKey);setName("");setEmail("");setMax(1);await onRefresh()}
  async function copy(v:string){await navigator.clipboard.writeText(v)}
  return <><div className="page-title"><div><h1>Licenses</h1><p>Generate and manage customer license keys.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={16}/> Generate License</button></div><div className="toolbar"><div className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search licenses..."/></div><span className="muted">{filtered.length} license(s)</span></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>License Key</th><th>Customer</th><th>Type</th><th>Status</th><th>Devices</th><th>Expires</th><th>Actions</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td><div className="key-cell"><KeyRound size={14}/><code>{l.licenseKey}</code><button className="mini-button" onClick={()=>copy(l.licenseKey)}><Copy size={13}/></button></div></td><td><strong>{l.customerName||"—"}</strong><small>{l.customerEmail}</small></td><td>{l.type}</td><td><StatusBadge status={l.status}/></td><td>{l.activeActivations} / {l.maxActivations}</td><td>{l.isLifetime?"Lifetime":formatDate(l.expiresAt)}</td><td><div className="actions">{l.status!=="revoked"&&<button className="mini-button" title="Suspend/Activate" onClick={async()=>{await updateLicenseStatus(l.id,l.status==="suspended"?"active":"suspended");await onRefresh()}}><RefreshCw size={14}/></button>}{!l.isLifetime&&<button className="mini-button" title="Renew" onClick={async()=>{await renewLicense(l.id,l.type==="yearly"?12:1);await onRefresh()}}>+1</button>}<button className="mini-button danger" title="Delete" onClick={async()=>{if(confirm("Delete this license?")){await deleteLicense(l.id);await onRefresh()}}}><Trash2 size={14}/></button></div></td></tr>)}{!filtered.length&&<tr><td colSpan={7}><div className="empty">No licenses found.</div></td></tr>}</tbody></table></div></section>
  {open&&<Modal title="Generate License" onClose={()=>setOpen(false)}><form className="form" onSubmit={submit}><label>License Type<select value={type} onChange={e=>setType(e.target.value as LicenseType)}><option value="trial">Trial</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="lifetime">Lifetime</option></select></label><label>Maximum Activations<input type="number" min={1} value={max} onChange={e=>setMax(Number(e.target.value))}/></label><label>Customer Name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Customer Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button"><KeyRound size={15}/> Generate</button></div></form></Modal>}
  {created&&<Modal title="License Created" onClose={()=>setCreated("")}><div className="generated"><div className="success-box">License generated successfully.</div><label>License key</label><div className="generated-key"><code>{created}</code><button className="mini-button" onClick={()=>copy(created)}><Copy size={15}/></button></div><p className="warning">Keep this key safe and send it to the customer.</p><button className="primary-button full" onClick={()=>setCreated("")}>Done</button></div></Modal>}</>;
}